/*******************************************************************************
*   Ledger Blue
*   (c) 2016 Ledger
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
********************************************************************************/

#include "os.h"
#include "cx.h"
#include <stdbool.h>

#include "os_io_seproxyhal.h"
#include "string.h"

#include "glyphs.h"
#include "base58.h"

unsigned int io_seproxyhal_touch_sign_ok(const bagl_element_t *e);
unsigned int io_seproxyhal_touch_sign_cancel(const bagl_element_t *e);
unsigned int io_seproxyhal_touch_address_ok(const bagl_element_t *e);
unsigned int io_seproxyhal_touch_address_cancel(const bagl_element_t *e);

#define MIN_BIP32_PATH 3
#define MAX_BIP32_PATH 4
#define MAX_USER_NAME 20

#define CLA 0x80
#define INS_GET_PUBLIC_KEY 0x02
#define INS_SIGN_TX 0x04
#define P1_FIRST 0x00
#define P1_NEXT 0x01
#define P1_LAST_MARKER 0x80

#define P1_CONFIRM 0x00
#define P1_NO_CONFIRM 0x01
#define P1_SIGNATURE 0x80

#define P2_MAINNET 0x00
#define P2_TESTNET 0x01

#define OFFSET_CLA 0
#define OFFSET_INS 1
#define OFFSET_P1 2
#define OFFSET_P2 3
#define OFFSET_LC 4
#define OFFSET_CDATA 5

#define MAINNET_PUBKEY_VARIANT 17
#define TESTNET_PUBKEY_VARIANT 19

#define COLOR_BG_1 0xF9F9F9
#define COLOR_BLACK 0x000000
#define COLOR_WHITE 0xFFFFFF
#define COLOR_GRAY 0x999999
#define COLOR_LIGHT_GRAY 0xEEEEEE

// NOTE: UI DEFINITION
#define UI_NANOS_BACKGROUND() {{BAGL_RECTANGLE,0,0,0,128,32,0,0,BAGL_FILL,0,COLOR_WHITE,0,0},NULL,0,0,0,NULL,NULL,NULL}
#define UI_NANOS_ICON_LEFT(userid, glyph) {{BAGL_ICON,userid,3,12,7,7,0,0,0,COLOR_WHITE,0,0,glyph},NULL,0,0,0,NULL,NULL,NULL}
#define UI_NANOS_ICON_RIGHT(userid, glyph) {{BAGL_ICON,userid,117,13,8,6,0,0,0,COLOR_WHITE,0,0,glyph},NULL,0,0,0,NULL,NULL,NULL}
#define UI_NANOS_TEXT(userid, x, y, w, text, font) {{BAGL_LABELINE,userid,x,y,w,32,0,0,0,COLOR_WHITE,0,font|BAGL_FONT_ALIGNMENT_CENTER,0},(char *)text,0,0,0,NULL,NULL,NULL}
// Only one scrolling text per screen can be displayed
#define UI_NANOS_SCROLLING_TEXT(userid, x, y, w, text, font) {{BAGL_LABELINE,userid,x,y,w,12,0x80|10,0,0,COLOR_WHITE,0,font|BAGL_FONT_ALIGNMENT_CENTER,26},(char *)text,0,0,0,NULL,NULL,NULL}

unsigned char G_io_seproxyhal_spi_buffer[IO_SEPROXYHAL_BUFFER_SIZE_B];

#ifdef TARGET_NANOX
#include "ux.h"
    ux_state_t G_ux;
    bolos_ux_params_t G_ux_params;
#else // TARGET_NANOX
    ux_state_t ux;
#endif // TARGET_NANOX

// display stepped screens
unsigned int ux_step;
unsigned int ux_step_count;
uint8_t ux_loop_over_curr_element; // Nano S only

#define MAX_MSG 255
#define TX_ID_SIZE 65
#define MAX_SIGN_TEXT 20
#define BITMARK_ACCOUNT_SIZE 52
#define HASH_SIZE 64

// NOTE: HEX Strings
static char hexlut[17] = "0123456789abcdef";

static const uint8_t pubkey_variant[2] = {MAINNET_PUBKEY_VARIANT, TESTNET_PUBKEY_VARIANT};

// NOTE: Menu Sesstion
// Here we define the main menu, using the Ledger-provided menu API. This menu
// turns out to be fairly unimportant for Nano S apps, since commands are sent
// by the computer instead of being initiated by the user. It typically just
// contains an idle screen and a version screen.

// This is a forward declaration, since menu_about needs to reference
// menu_main.
static const ux_menu_entry_t menu_main[];

static const ux_menu_entry_t menu_about[] = {
	// I won't bother describing how menus work in detail, since it's fairly
	// self-evident and not very useful; but to save you some trouble, this
	// first element is defined with explicit fields, so you can see what they
	// all are.
	{
		.menu     = NULL,       // another menu entry, displayed when this item is "entered"
		.callback = NULL,       // a function that takes a userid, called when this item is entered
		.userid   = 0,          // a custom identifier, helpful for implementing custom menu behavior
		.icon     = NULL,       // the glyph displayed next to the item text
		.line1    = "Version",  // the first line of text
		.line2    = APPVERSION, // the second line of text; if NULL, line1 will be vertically centered
		.text_x   = 0,          // the x offset of the lines of text; only used if non-zero
		.icon_x   = 0,          // the x offset of the icon; only used if non-zero
	},
	// This element references a custom glyph, C_icon_back. This glyph is
	// defined in glyphs.c, which was generated by the Makefile from the
	// corresponding .gif file in the glyphs/ folder. If you drop your own
	// .gif files into this folder and run make, they will likewise become
	// available for use in your app. The SDK also defines a few built-in
	// icons, such as BAGL_GLYPH_ICON_CHECK, which you'll see in the screen
	// definitions later on.
	{menu_main, NULL, 0, &C_icon_back, "Back", NULL, 61, 40},
	UX_MENU_END,
};

static const ux_menu_entry_t menu_main[] = {
	{NULL, NULL, 0, &C_icon_bitmark_logo, "Waiting for", "commands...", 0, 8},
	{menu_about, NULL, 0, NULL, "About", NULL, 0, 0},
	{NULL, os_sched_exit, 0, &C_icon_dashboard, "Quit app", NULL, 50, 29},
	UX_MENU_END,
};

// NOTE: End of menu


// NOTE: transaction contexts

typedef struct issue_context_t {
    char asset_id[51];
} issue_context_t;

typedef struct transfer_context_t {
    char tx_id[TX_ID_SIZE];
    char new_owner[BITMARK_ACCOUNT_SIZE];
} transfer_context_t;


// NOTE: app context
typedef struct app_context_t {
    uint8_t pathLength;
    uint32_t bip32Path[MAX_BIP32_PATH];
    cx_ecfp_public_key_t publicKey;
    uint8_t message[MAX_MSG];
    uint32_t messageLength;
    bool returnSignature;
    char bitmarkAccount[BITMARK_ACCOUNT_SIZE];
    uint8_t accountSignature[HASH_SIZE];
    char signText[MAX_SIGN_TEXT];
    issue_context_t issue;
    transfer_context_t transfer;
} app_context_t;

// Initialize ledger context
app_context_t appContext;

// NOTE: Button Session


// ui_idle displays the main menu. Note that your app isn't required to use a
// menu as its idle screen; you can define your own completely custom screen.
void ui_idle(void) {
    ux_step_count = 0;
    ux_loop_over_curr_element = 0;
    os_memset(appContext.signText, 0, MAX_SIGN_TEXT);
	// The first argument is the starting index within menu_main, and the last
	// argument is a preprocessor; I've never seen an app that uses either
	// argument.
	UX_MENU_DISPLAY(0, menu_main, NULL);
}

static const char SIGN_TEXT_PREFIX[5] = "Sign ";
static const char ISSUE_TX[5] = "Issue";
static const char TRANSFER_TX[8] = "Transfer";




const bagl_element_t ui_address_nanos[] = {
    UI_NANOS_BACKGROUND(),

    UI_NANOS_ICON_LEFT(0x01, BAGL_GLYPH_ICON_CROSS),
    UI_NANOS_ICON_RIGHT(0x01, BAGL_GLYPH_ICON_CHECK),
    UI_NANOS_TEXT(0x01, 0, 12, 128, "Confirm", BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),
    UI_NANOS_TEXT(0x01, 0, 26, 128, "Account", BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),

    UI_NANOS_TEXT(0x02, 0, 12, 128, "Bitmark Account", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_SCROLLING_TEXT(0x82, 14, 26, 100, appContext.bitmarkAccount, BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),
};

const bagl_element_t *ui_address_prepro(const bagl_element_t *element) {
    if (element->component.userid > 0) {
        unsigned int display = (ux_step == (0x7F & element->component.userid) - 1);
        if (display) {
            switch (element->component.userid) {
            case 1:
                UX_CALLBACK_SET_INTERVAL(2000);
                ux_loop_over_curr_element = 0; // allow next timer to increment ux_step when triggered
                break;
            case 0x82:
                UX_CALLBACK_SET_INTERVAL(MAX(3000, 1000 + bagl_label_roundtrip_duration_ms(element, 7)));
                // ugly ux tricks, loops around last 2 screens
                ux_step -= 1; // loops back to previous element on next redraw
                ux_loop_over_curr_element = 1; // when the timer will trigger, ux_step won't be incremented, only redraw
                break;
            }
            return element;
        } else {
            return NULL;
        }
    }
    return element;
}

unsigned int ui_address_nanos_button(unsigned int button_mask, unsigned int button_mask_counter);

unsigned int ui_address_nanos_button(unsigned int button_mask, unsigned int button_mask_counter) {
    switch (button_mask) {
    case BUTTON_EVT_RELEASED | BUTTON_LEFT: // CANCEL
        io_seproxyhal_touch_address_cancel(NULL);
        break;

    case BUTTON_EVT_RELEASED | BUTTON_RIGHT: { // OK
        io_seproxyhal_touch_address_ok(NULL);
        break;
    }
    }
    return 0;
};

const bagl_element_t ui_sign_tx_nanos[] = {
    UI_NANOS_BACKGROUND(),

    // Issue transaction
    UI_NANOS_ICON_LEFT(0x1, BAGL_GLYPH_ICON_CROSS),
    UI_NANOS_ICON_RIGHT(0x1, BAGL_GLYPH_ICON_CHECK),
    UI_NANOS_TEXT(0x1, 0, 12, 128, (char *)appContext.signText, BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_TEXT(0x1, 0, 26, 128, "Transaction", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_TEXT(0x2, 0, 12, 128, "Asset ID", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_SCROLLING_TEXT(0x82, 14, 26, 100, (char *)appContext.issue.asset_id, BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),

    // Transfer transaction
    UI_NANOS_ICON_LEFT(0x5, BAGL_GLYPH_ICON_CROSS),
    UI_NANOS_ICON_RIGHT(0x5, BAGL_GLYPH_ICON_CHECK),
    UI_NANOS_TEXT(0x5, 0, 12, 128, (char *)appContext.signText, BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_TEXT(0x5, 0, 26, 128, "Transaction", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_TEXT(0x6, 0, 12, 128, "TX ID", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_SCROLLING_TEXT(0x86, 14, 26, 100, (char *)appContext.transfer.tx_id, BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),
    UI_NANOS_TEXT(0x7, 0, 12, 128, "To Account", BAGL_FONT_OPEN_SANS_REGULAR_11px),
    UI_NANOS_SCROLLING_TEXT(0x87, 14, 26, 100, (char *)appContext.transfer.new_owner, BAGL_FONT_OPEN_SANS_EXTRABOLD_11px),
};


const bagl_element_t *ui_sign_tx_prepro(const bagl_element_t *element) {
    if (element->component.userid > 0) {
        unsigned int display = (ux_step == (0x7F & element->component.userid) - 1);
        if (display) {
            switch (element->component.userid) {
            case 1:
                UX_CALLBACK_SET_INTERVAL(2000);
                ux_loop_over_curr_element = 0; // allow next timer to increment ux_step when triggered
                break;
            case 0x82:
                UX_CALLBACK_SET_INTERVAL(MAX(3000, 1000 + bagl_label_roundtrip_duration_ms(element, 7)));
                // ugly ux tricks, loops around last 2 screens
                ux_step -= 1; // loops back to previous element on next redraw
                ux_loop_over_curr_element = 1; // when the timer will trigger, ux_step won't be incremented, only redraw
                break;
            case 5:
                UX_CALLBACK_SET_INTERVAL(2000);
                ux_loop_over_curr_element = 0; // allow next timer to increment ux_step when triggered
                break;
             case 0x86:
                UX_CALLBACK_SET_INTERVAL(MAX(3000, 1000 + bagl_label_roundtrip_duration_ms(element, 7)));
                ux_loop_over_curr_element = 0; // allow next timer to increment ux_step when triggered
                break;
             case 0x87:
                UX_CALLBACK_SET_INTERVAL(MAX(3000, 1000 + bagl_label_roundtrip_duration_ms(element, 7)));
                // ugly ux tricks, loops around last 2 screens
                ux_step -= 2; // loops back to previous element on next redraw
                ux_loop_over_curr_element = 1; // when the timer will trigger, ux_step won't be incremented, only redraw
                break;
            }
            return element;
        } else {
            return NULL;
        }
    }
    return element;
}

unsigned int ui_sign_tx_nanos_button(unsigned int button_mask, unsigned int button_mask_counter);

unsigned int ui_sign_tx_nanos_button(unsigned int button_mask, unsigned int button_mask_counter) {
    switch (button_mask) {
    case BUTTON_EVT_RELEASED | BUTTON_LEFT: // CANCEL
        io_seproxyhal_touch_sign_cancel(NULL);
        break;

    case BUTTON_EVT_RELEASED | BUTTON_RIGHT: { // OK
        io_seproxyhal_touch_sign_ok(NULL);
        break;
    }
    }
    return 0;
};

// NOTE: End of Button Session

unsigned int bin2hex(char *out, size_t out_sz, uint8_t *in, size_t in_sz) {
    if (in_sz*2 + 1>out_sz) {
        return 0;
    }
    uint8_t i;
    for (i = 0; i < in_sz; i++) {
        out[2*i] = hexlut[(in[i]>>4) & 0x0F];
        out[2*i+1] = hexlut[in[i] & 0x0f];
    }
    out[2*i] = '\0';
    return in_sz*2+1;
}


void extractPubkeyBytes(uint8_t *out, cx_ecfp_public_key_t *publicKey) {
    // copy public key little endian to big endian
	for (int i = 0; i < 32; i++) {
		out[i] = publicKey->W[64 - i];
	}

    // set sign bit
	if (publicKey->W[32] & 1) {
		out[31] |= 0x80;
	}
}

// pubkeyToBitmarkAccount turns a 32-byte public key and a 1-byte key variant
// into a base58 encoded bitmark account
void pubkeyToBitmarkAccount(char *out, uint8_t keyVariant, uint8_t *pubkey) {
    uint8_t account[37];
    uint8_t checksum[32];

    account[0] = keyVariant;
    os_memmove(account+1, pubkey, 32);

    cx_sha3_t sha3;
    cx_sha3_init(&sha3, 256);
    cx_hash((cx_hash_t*)(&sha3), CX_LAST, account, 33, checksum);
    os_memmove(account+33, checksum, 4);

    size_t out_sz;
    b58enc(out, &out_sz, account, sizeof(account));
}

// print_summary accepts an input string and outputs a shrinked version
// of origin string
void print_summary(char *out, char *in, uint8_t numCharsL, uint8_t numCharsR) {
    uint8_t outLength = numCharsL + numCharsR + 3;
    uint16_t inLength = strlen(in);
    if (inLength > outLength) {
        os_memmove(out, in, numCharsL);
        out[numCharsL] = '.';
        out[numCharsL+1] = '.';
        out[numCharsL+2] = '.';
        os_memmove(out + numCharsL+3, in + inLength - numCharsR, numCharsR);
        out[outLength] = '\0';
    } else {
        os_memmove(out, in, inLength);
    }
}

unsigned int io_seproxyhal_touch_sign_ok(const bagl_element_t *e) {
    uint8_t seed_bytes[32];
    cx_ecfp_private_key_t privateKey;
    uint32_t tx = 0;


#ifdef TARGET_BLUE
    os_perso_derive_node_bip32(CX_CURVE_Ed25519, appContext.bip32Path, appContext.pathLength, seed_bytes, NULL);
#else
    os_perso_derive_node_bip32_seed_key(HDW_ED25519_SLIP10, CX_CURVE_Ed25519, appContext.bip32Path, appContext.pathLength, seed_bytes, NULL, (unsigned char*) "ed25519 seed", 12);
#endif

    cx_ecfp_init_private_key(CX_CURVE_Ed25519, seed_bytes, 32,
                             &privateKey);
    os_memset(seed_bytes, 0, sizeof(seed_bytes));

#if CX_APILEVEL >= 8
    tx = cx_eddsa_sign(
        &privateKey, CX_LAST, CX_SHA512, appContext.message,
        appContext.messageLength, NULL, 0, G_io_apdu_buffer, NULL);
#else
    tx = cx_eddsa_sign(
        &privateKey, NULL, CX_LAST, CX_SHA512, appContext.message,
        appContext.messageLength, G_io_apdu_buffer);
#endif

    os_memset(&privateKey, 0, sizeof(privateKey));
    os_memset(&seed_bytes, 0, sizeof(seed_bytes));
    G_io_apdu_buffer[tx++] = 0x90;
    G_io_apdu_buffer[tx++] = 0x00;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, tx);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}

unsigned int io_seproxyhal_touch_sign_cancel(const bagl_element_t *e) {
    G_io_apdu_buffer[0] = 0x69;
    G_io_apdu_buffer[1] = 0x85;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, 2);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}

unsigned int io_seproxyhal_touch_address_ok(const bagl_element_t *e) {
    uint32_t tx = 0;
    extractPubkeyBytes(G_io_apdu_buffer + tx, &appContext.publicKey);
    tx += 32;

    if (appContext.returnSignature) {
        os_memmove(G_io_apdu_buffer + tx, appContext.accountSignature, 64);
        tx += 64;
    }

    G_io_apdu_buffer[tx++] = 0x90;
    G_io_apdu_buffer[tx++] = 0x00;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, tx);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}

unsigned int io_seproxyhal_touch_address_cancel(const bagl_element_t *e) {
    G_io_apdu_buffer[0] = 0x69;
    G_io_apdu_buffer[1] = 0x85;
    // Send back the response, do not restart the event loop
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, 2);
    // Display back the original UX
    ui_idle();
    return 0; // do not redraw the widget
}



unsigned short io_exchange_al(unsigned char channel, unsigned short tx_len) {
    switch (channel & ~(IO_FLAGS)) {
    case CHANNEL_KEYBOARD:
        break;

    // multiplexed io exchange over a SPI channel and TLV encapsulated protocol
    case CHANNEL_SPI:
        if (tx_len) {
            io_seproxyhal_spi_send(G_io_apdu_buffer, tx_len);

            if (channel & IO_RESET_AFTER_REPLIED) {
                reset();
            }
            return 0; // nothing received from the master so far (it's a tx
                      // transaction)
        } else {
            return io_seproxyhal_spi_recv(G_io_apdu_buffer,
                                          sizeof(G_io_apdu_buffer), 0);
        }

    default:
        THROW(INVALID_PARAMETER);
    }
    return 0;
}


void bip_read_path(uint32_t *path, uint8_t *dataBuffer) {
    *path =
        (dataBuffer[0] << 24) | (dataBuffer[1] << 16) |
        (dataBuffer[2] << 8) | (dataBuffer[3]);
}

void app_main(void) {
    volatile unsigned int rx = 0;
    volatile unsigned int tx = 0;
    volatile unsigned int flags = 0;

    // DESIGN NOTE: the bootloader ignores the way APDU are fetched. The only
    // goal is to retrieve APDU.
    // When APDU are to be fetched from multiple IOs, like NFC+USB+BLE, make
    // sure the io_event is called with a
    // switch event, before the apdu is replied to the bootloader. This avoid
    // APDU injection faults.
    for (;;) {
        volatile unsigned short sw = 0;

        BEGIN_TRY {
            TRY {
                rx = tx;
                tx = 0; // ensure no race in catch_other if io_exchange throws
                        // an error
                rx = io_exchange(CHANNEL_APDU | flags, rx);
                flags = 0;

                // no apdu received, well, reset the session, and reset the
                // bootloader configuration
                if (rx == 0) {
                    THROW(0x6982);
                }

                if (G_io_apdu_buffer[0] != CLA) {
                    THROW(0x6E00);
                }

                switch (G_io_apdu_buffer[1]) {
                case INS_GET_PUBLIC_KEY: {
                    uint8_t p1 = G_io_apdu_buffer[OFFSET_P1];
                    uint8_t p2 = G_io_apdu_buffer[OFFSET_P2];
                    uint8_t seed_bytes[32];
                    uint32_t i;
                    uint32_t dataLength = G_io_apdu_buffer[OFFSET_LC] - 1;
                    uint8_t *dataBuffer = G_io_apdu_buffer + OFFSET_CDATA + 1;
                    cx_ecfp_private_key_t privateKey;

                    appContext.returnSignature = ((p1 & P1_SIGNATURE) != 0);
                    p1 &= ~P1_SIGNATURE;

                    if ((p1 != P1_CONFIRM) && (p1 != P1_NO_CONFIRM)){
                        THROW(0x6B00);
                    }

                    if ((p2 != P2_MAINNET) && (p2 != P2_TESTNET)) {
                        THROW(0x6B00);
                    }

                    appContext.pathLength =
                        G_io_apdu_buffer[OFFSET_CDATA];
                    if ((appContext.pathLength < MIN_BIP32_PATH) ||
                        (appContext.pathLength > MAX_BIP32_PATH)) {
                        THROW(0x6a80);
                    }

                    for (i = 0; i < appContext.pathLength; i++) {
                        bip_read_path(appContext.bip32Path + i, dataBuffer);
                        dataBuffer += 4;
                        dataLength -= 4;
                    }

#ifdef TARGET_BLUE
                    os_perso_derive_node_bip32(CX_CURVE_Ed25519, appContext.bip32Path, appContext.pathLength, seed_bytes, NULL);
#else
                    // new api since nanos firmware 1.5.5
                    os_perso_derive_node_bip32_seed_key(HDW_ED25519_SLIP10, CX_CURVE_Ed25519, appContext.bip32Path, appContext.pathLength, seed_bytes, NULL, (unsigned char*) "ed25519 seed", 12);
#endif
                    cx_ecfp_init_private_key(CX_CURVE_Ed25519, seed_bytes, 32, &privateKey);
                    cx_ecfp_generate_pair(CX_CURVE_Ed25519, &appContext.publicKey, &privateKey, 1);

                    uint8_t publicKey[32];
                    extractPubkeyBytes(publicKey, &appContext.publicKey);
                    pubkeyToBitmarkAccount(appContext.bitmarkAccount, pubkey_variant[p2], publicKey);

                    if (appContext.returnSignature) {
                        if (dataLength > 32) {
                            THROW(0x6a80);
                        }
#if CX_APILEVEL >= 8
                        tx = cx_eddsa_sign(
                            &privateKey, CX_LAST, CX_SHA512, dataBuffer,
                            dataLength, NULL, 0, appContext.accountSignature, NULL);
#else
                        tx = cx_eddsa_sign(
                            &privateKey, NULL, CX_LAST, CX_SHA512, dataBuffer,
                            dataLength, appContext.accountSignature);
#endif
                    }

                    os_memset(seed_bytes, 0, sizeof(seed_bytes));
                    os_memset(&privateKey, 0, sizeof(privateKey));

                    ux_step = 0;
                    ux_step_count = 2;
                    UX_DISPLAY(ui_address_nanos, ui_address_prepro);

                    flags |= IO_ASYNCH_REPLY;
                }

                break;

                case INS_SIGN_TX: {
                    uint8_t p1 = G_io_apdu_buffer[OFFSET_P1];
                    uint8_t p2 = G_io_apdu_buffer[OFFSET_P2];
                    uint8_t *dataBuffer = G_io_apdu_buffer + OFFSET_CDATA;
                    uint32_t dataLength = G_io_apdu_buffer[OFFSET_LC];

                    if ((p2 != P2_MAINNET) && (p2 != P2_TESTNET)) {
                        THROW(0x6B00);
                    }

                    bool last = ((p1 & P1_LAST_MARKER) != 0);
                    p1 &= ~P1_LAST_MARKER;

                    // Reset data and get bip32 path for first APDU buffer
                    if (p1 == P1_FIRST) {
                        uint32_t i;
                        appContext.pathLength = *dataBuffer;
                        dataBuffer++;
                        dataLength--;
                        if ((appContext.pathLength < MIN_BIP32_PATH) ||
                            (appContext.pathLength > MAX_BIP32_PATH)) {
                            THROW(0x6a80);
                        }
                        for (i = 0; i < appContext.pathLength; i++) {
                            bip_read_path(appContext.bip32Path + i, dataBuffer);
                            dataBuffer += 4;
                            dataLength -= 4;
                        }
                        appContext.messageLength = 0;

                    } else if (p1 != P1_NEXT) {
                        THROW(0x6B00);
                    }

                    uint32_t offset = appContext.messageLength;
                    os_memmove(appContext.message+offset, dataBuffer, dataLength);
                    appContext.messageLength += dataLength;

                    if (!last) {
                        THROW(0x9000);
                    }

                    // All data get
                    os_memmove(appContext.signText, SIGN_TEXT_PREFIX, sizeof(SIGN_TEXT_PREFIX));
                    switch (appContext.message[0])
                    {
                    case 3:

                        os_memmove(appContext.signText + 5, ISSUE_TX, sizeof(ISSUE_TX));
                        ux_step = 0;

                        // Check length of a target asset
                        if (appContext.message[1] != 0x40) {
                            THROW(0x6801); // invalid asset_id buffer size
                        }

                        // Check length of a target account
                        if (appContext.message[66] != 0x21)  {
                            THROW(0x6801); // invalid account buffer size
                        }

                        // Check network bits of issuer accounts
                        if (appContext.message[67] != pubkey_variant[p2]) {
                            THROW(0x6802); // invalid network
                        }

                        char asset_id[129];
                        bin2hex(asset_id, sizeof(asset_id), appContext.message + 2, 64);
                        print_summary(appContext.issue.asset_id, asset_id, 20, 20);

                        break;
                    case 4:
                        os_memmove(appContext.signText + 5, TRANSFER_TX, sizeof(TRANSFER_TX));
                        ux_step = 4;

                        // Check length of a target transaction id
                        if (appContext.message[1] != 0x20) {
                            THROW(0x6801); // invalid tx_id buffer size
                        }
                        bin2hex(appContext.transfer.tx_id, TX_ID_SIZE, appContext.message + 2, 32);

                        // Check length of a target account
                        if (appContext.message[35] != 0x21)  {
                            THROW(0x6801); // invalid account buffer size
                        }

                        // Check network bits of new owner accounts
                        if (appContext.message[36] != pubkey_variant[p2]) {
                            THROW(0x6802); // invalid network
                        }

                        pubkeyToBitmarkAccount(appContext.transfer.new_owner, pubkey_variant[p2], appContext.message + 37);

                        break;
                    default:
                        THROW(0x6800);
                        break;
                    }

                    ux_step_count = 8;
                    UX_DISPLAY(ui_sign_tx_nanos, ui_sign_tx_prepro);

                    flags |= IO_ASYNCH_REPLY;
                }

                break;

                default:
                    THROW(0x6D00);
                    break;
                }
            }
            CATCH_OTHER(e) {
                switch (e & 0xF000) {
                case 0x6000:
                case 0x9000:
                    sw = e;
                    break;
                default:
                    sw = 0x6800 | (e & 0x7FF);
                    break;
                }
                // Unexpected exception => report
                G_io_apdu_buffer[tx] = sw >> 8;
                G_io_apdu_buffer[tx + 1] = sw;
                tx += 2;
            }
            FINALLY {
            }
        }
        END_TRY;
    }
}

void io_seproxyhal_display(const bagl_element_t *element) {
    return io_seproxyhal_display_default((bagl_element_t *)element);
}

unsigned char io_event(unsigned char channel) {
    // nothing done with the event, throw an error on the transport layer if
    // needed

    // can't have more than one tag in the reply, not supported yet.
    switch (G_io_seproxyhal_spi_buffer[0]) {
    case SEPROXYHAL_TAG_FINGER_EVENT:
        UX_FINGER_EVENT(G_io_seproxyhal_spi_buffer);
        break;

    case SEPROXYHAL_TAG_BUTTON_PUSH_EVENT:
        UX_BUTTON_PUSH_EVENT(G_io_seproxyhal_spi_buffer);
        break;

#ifdef HAVE_BLE
    // Make automatically discoverable again when disconnected

    case SEPROXYHAL_TAG_BLE_CONNECTION_EVENT:
        if (G_io_seproxyhal_spi_buffer[3] == 0) {
            // TODO : cleaner reset sequence
            // first disable BLE before turning it off
            G_io_seproxyhal_spi_buffer[0] = SEPROXYHAL_TAG_BLE_RADIO_POWER;
            G_io_seproxyhal_spi_buffer[1] = 0;
            G_io_seproxyhal_spi_buffer[2] = 1;
            G_io_seproxyhal_spi_buffer[3] = 0;
            io_seproxyhal_spi_send(G_io_seproxyhal_spi_buffer, 4);
            // send BLE power on (default parameters)
            G_io_seproxyhal_spi_buffer[0] = SEPROXYHAL_TAG_BLE_RADIO_POWER;
            G_io_seproxyhal_spi_buffer[1] = 0;
            G_io_seproxyhal_spi_buffer[2] = 1;
            G_io_seproxyhal_spi_buffer[3] = 3; // ble on & advertise
            io_seproxyhal_spi_send(G_io_seproxyhal_spi_buffer, 5);
        }
        break;
#endif

    case SEPROXYHAL_TAG_DISPLAY_PROCESSED_EVENT:
        UX_DISPLAYED_EVENT({});
        break;

    case SEPROXYHAL_TAG_TICKER_EVENT:
        UX_TICKER_EVENT(G_io_seproxyhal_spi_buffer, {
            // don't redisplay if UX not allowed (pin locked in the common bolos
            // ux ?)
            if (ux_step_count && UX_ALLOWED) {
                // prepare next screen
                if(!ux_loop_over_curr_element) {
                    ux_step = (ux_step + 1) % ux_step_count;
                }
                // redisplay screen
                UX_REDISPLAY();
            }
        });
        break;

    // unknown events are acknowledged
    default:
        UX_DEFAULT_EVENT();
        break;
    }

    // close the event if not done previously (by a display or whatever)
    if (!io_seproxyhal_spi_is_status_sent()) {
        io_seproxyhal_general_status();
    }
    // command has been processed, DO NOT reset the current APDU transport
    return 1;
}

void app_exit(void) {
    BEGIN_TRY_L(exit) {
        TRY_L(exit) {
            os_sched_exit(-1);
        }
        FINALLY_L(exit) {
        }
    }
    END_TRY_L(exit);
}

__attribute__((section(".boot"))) int main(void) {
    // exit critical section
    __asm volatile("cpsie i");

    UX_INIT();

    // ensure exception will work as planned
    os_boot();

    BEGIN_TRY {
        TRY {
            io_seproxyhal_init();

#ifdef TARGET_NANOX
            // grab the current plane mode setting
            G_io_app.plane_mode = os_setting_get(OS_SETTING_PLANEMODE, NULL, 0);
#endif // TARGET_NANOX

            USB_power(0);
            USB_power(1);

            ui_idle();

#ifdef HAVE_BLE
            BLE_power(0, NULL);
            BLE_power(1, "Nano X");
#endif // HAVE_BLE

            app_main();
        }
        CATCH_OTHER(e) {
        }
        FINALLY {
        }
    }
    END_TRY;

    app_exit();
}
